export const columnsExample = [
  { title: "First Name", data: "firstName" },
  { title: "Last Name", data: "lastName" },
  { title: "Start Date", data: "startDate" },
  { title: "Department", data: "department" },
  { title: "Date of Birth", data: "dateOfBirth" },
  { title: "Street", data: "street" },
  { title: "City", data: "city" },
  { title: "State", data: "state" },
  { title: "Zip Code", data: "zipCode" },
];

export const dataExample = [
  {
    firstName: "Aron",
    lastName: "Test",
    dateOfBirth: "06/17/1993",
    startDate: "07/10/2023",
    department: "Marketing",
    street: "Rue du stade",
    city: "The city",
    state: "AL",
    zipCode: "00000",
  },
  {
    firstName: "Bob",
    lastName: "Test 2",
    dateOfBirth: "05/15/1999",
    startDate: "07/08/2023",
    department: "Sales",
    street: "Grande rue",
    city: "New-York",
    state: "NY",
    zipCode: "10000",
  },
  {
    firstName: "Cathy",
    lastName: "Test 3",
    dateOfBirth: "05/19/1991",
    startDate: "07/08/2023",
    department: "Sales",
    street: "Grande rue",
    city: "New-York",
    state: "NY",
    zipCode: "10000",
  },
  {
    firstName: "Aron2",
    lastName: "Test",
    dateOfBirth: "06/15/1993",
    startDate: "07/10/2023",
    department: "Marketing",
    street: "Rue du stade",
    city: "The city",
    state: "AL",
    zipCode: "00000",
  },
  {
    firstName: "Bob",
    lastName: "Test 2",
    dateOfBirth: "05/15/1999",
    startDate: "07/08/2023",
    department: "Sales",
    street: "Grande rue",
    city: "New-York",
    state: "NY",
    zipCode: "10000",
  },
  {
    firstName: "Cathy",
    lastName: "Test 3",
    dateOfBirth: "05/19/1991",
    startDate: "07/08/2023",
    department: "Sales",
    street: "Grande rue",
    city: "New-York",
    state: "NY",
    zipCode: "10000",
  },
  {
    firstName: "Aron3",
    lastName: "Test",
    dateOfBirth: "06/12/1993",
    startDate: "07/10/2023",
    department: "Marketing",
    street: "Rue du stade",
    city: "The city",
    state: "AL",
    zipCode: "00000",
  },
  {
    firstName: "Bob",
    lastName: "Test 2",
    dateOfBirth: "05/15/1999",
    startDate: "07/08/2023",
    department: "Sales",
    street: "Grande rue",
    city: "New-York",
    state: "NY",
    zipCode: "10000",
  },
  {
    firstName: "Cathy",
    lastName: "Test 3",
    dateOfBirth: "05/19/1991",
    startDate: "07/08/2023",
    department: "Sales",
    street: "Grande rue",
    city: "New-York",
    state: "NY",
    zipCode: "10000",
  },
  {
    firstName: "Zinedine",
    lastName: "Zidane",
    dateOfBirth: "05/19/1987",
    startDate: "07/08/2021",
    department: "Sport",
    street: "Street",
    city: "Marseille",
    state: "13",
    zipCode: "13000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    dateOfBirth: "05/19/1975",
    startDate: "07/08/2015",
    department: "Tech",
    street: "George Street",
    city: "LA",
    state: "California",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "06/21/1985",
    startDate: "07/08/2014",
    department: "Industry",
    street: "George Street",
    city: "LA",
    state: "Mexique",
    zipCode: "000000",
  }
];
