export const sampleColumns = [
  { title: "First Name", data: "firstName" },
  { title: "Last Name", data: "lastName" },
  { title: "Date of Birth", data: "dateOfBirth" },
  { title: "Street", data: "street" },
  { title: "City", data: "city" },
  { title: "Zip Code", data: "zipCode" },
];

export const sampleData = [
  {
    firstName: "Aron",
    lastName: "Test",
    dateOfBirth: "06/17/1993",
    street: "Stadium street",
    city: "The city",
    zipCode: "00000",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    dateOfBirth: "03/25/1985",
    street: "123 Main Street",
    city: "New York",
    zipCode: "10001",
  },
  {
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "09/12/1978",
    street: "456 Elm Street",
    city: "Los Angeles",
    zipCode: "90001",
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    dateOfBirth: "11/30/1990",
    street: "789 Oak Avenue",
    city: "Chicago",
    zipCode: "60601",
  },
  {
    firstName: "Bob",
    lastName: "Brown",
    dateOfBirth: "07/05/1982",
    street: "101 Pine Road",
    city: "San Francisco",
    zipCode: "94101",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    dateOfBirth: "02/19/1995",
    street: "222 Cedar Lane",
    city: "Miami",
    zipCode: "33101",
  },
  {
    firstName: "David",
    lastName: "Wilson",
    dateOfBirth: "08/14/1987",
    street: "333 Birch Drive",
    city: "Houston",
    zipCode: "77001",
  },
  {
    firstName: "Grace",
    lastName: "Miller",
    dateOfBirth: "01/08/1980",
    street: "444 Willow Street",
    city: "Philadelphia",
    zipCode: "19101",
  },
  {
    firstName: "Michael",
    lastName: "Taylor",
    dateOfBirth: "04/22/1992",
    street: "555 Maple Avenue",
    city: "Boston",
    zipCode: "02101",
  },
  {
    firstName: "Olivia",
    lastName: "Martinez",
    dateOfBirth: "12/10/1984",
    street: "666 Spruce Lane",
    city: "Dallas",
    zipCode: "75201",
  },
  {
    firstName: "Ella",
    lastName: "Williams",
    dateOfBirth: "10/08/1991",
    street: "777 Willow Road",
    city: "San Diego",
    zipCode: "92101",
  },
  {
    firstName: "Liam",
    lastName: "Brown",
    dateOfBirth: "07/14/1986",
    street: "888 Oak Street",
    city: "Seattle",
    zipCode: "98101",
  },
  {
    firstName: "Sophia",
    lastName: "Jones",
    dateOfBirth: "03/27/1983",
    street: "999 Cedar Avenue",
    city: "Denver",
    zipCode: "80201",
  },
  {
    firstName: "Lucas",
    lastName: "White",
    dateOfBirth: "05/01/1990",
    street: "1010 Elm Drive",
    city: "Atlanta",
    zipCode: "30301",
  },
  {
    firstName: "Ava",
    lastName: "Anderson",
    dateOfBirth: "12/03/1988",
    street: "1111 Pine Lane",
    city: "Phoenix",
    zipCode: "85001",
  },
  {
    firstName: "Noah",
    lastName: "Davis",
    dateOfBirth: "09/18/1994",
    street: "1212 Birch Road",
    city: "Detroit",
    zipCode: "48201",
  },
  {
    firstName: "Mia",
    lastName: "Hernandez",
    dateOfBirth: "02/07/1982",
    street: "1313 Maple Street",
    city: "Minneapolis",
    zipCode: "55401",
  },
  {
    firstName: "Liam",
    lastName: "Garcia",
    dateOfBirth: "06/29/1993",
    street: "1414 Spruce Avenue",
    city: "San Antonio",
    zipCode: "78201",
  },
  {
    firstName: "Sophia",
    lastName: "Walker",
    dateOfBirth: "11/12/1985",
    street: "1515 Cedar Road",
    city: "Miami",
    zipCode: "33101",
  },
  {
    firstName: "Lucas",
    lastName: "Harris",
    dateOfBirth: "04/04/1989",
    street: "1616 Elm Lane",
    city: "Chicago",
    zipCode: "60601",
  },
  {
    firstName: "Brad",
    lastName: "Pitt",
    dateOfBirth: "12/18/1963",
    street: "123 Hollywood Blvd",
    city: "Los Angeles",
    zipCode: "90001",
  },
  {
    firstName: "Jennifer",
    lastName: "Aniston",
    dateOfBirth: "02/11/1969",
    street: "456 Sunset Ave",
    city: "Malibu",
    zipCode: "90263",
  },
  {
    firstName: "Leonardo",
    lastName: "DiCaprio",
    dateOfBirth: "11/11/1974",
    street: "789 Ocean Drive",
    city: "Santa Monica",
    zipCode: "90401",
  },
  {
    firstName: "Beyoncé",
    lastName: "Knowles",
    dateOfBirth: "09/04/1981",
    street: "101 Starlight Road",
    city: "Houston",
    zipCode: "77001",
  },
  {
    firstName: "Serena",
    lastName: "Williams",
    dateOfBirth: "09/26/1981",
    street: "222 Championship Lane",
    city: "Palm Beach Gardens",
    zipCode: "33418",
  },
  {
    firstName: "Oprah",
    lastName: "Winfrey",
    dateOfBirth: "01/29/1954",
    street: "333 Inspiration St",
    city: "Santa Barbara",
    zipCode: "93101",
  },
  {
    firstName: "Stephen",
    lastName: "King",
    dateOfBirth: "09/21/1947",
    street: "444 Horror Lane",
    city: "Bangor",
    zipCode: "04401",
  },
  {
    firstName: "Meryl",
    lastName: "Streep",
    dateOfBirth: "06/22/1949",
    street: "555 Awards Avenue",
    city: "New York",
    zipCode: "10001",
  },
  {
    firstName: "Keanu",
    lastName: "Reeves",
    dateOfBirth: "09/02/1964",
    street: "666 Action Blvd",
    city: "Los Angeles",
    zipCode: "90001",
  },
  {
    firstName: "Tom",
    lastName: "Hanks",
    dateOfBirth: "07/09/1956",
    street: "777 Forrest Road",
    city: "Burbank",
    zipCode: "91501",
  },
  {
    firstName: "Angelina",
    lastName: "Jolie",
    dateOfBirth: "06/04/1975",
    street: "123 Star Ave",
    city: "Los Angeles",
    zipCode: "90001",
  },
  {
    firstName: "George",
    lastName: "Clooney",
    dateOfBirth: "05/06/1961",
    street: "456 Fame Blvd",
    city: "Beverly Hills",
    zipCode: "90210",
  },
  {
    firstName: "Natalie",
    lastName: "Portman",
    dateOfBirth: "06/09/1981",
    street: "789 Red Carpet St",
    city: "Hollywood",
    zipCode: "90028",
  },
  {
    firstName: "Johnny",
    lastName: "Depp",
    dateOfBirth: "06/09/1963",
    street: "101 Pirate Lane",
    city: "Los Angeles",
    zipCode: "90001",
  },
  {
    firstName: "Emma",
    lastName: "Watson",
    dateOfBirth: "04/15/1990",
    street: "222 Magic Road",
    city: "London",
    zipCode: "SW1A 1AA",
  },
  {
    firstName: "Chris",
    lastName: "Hemsworth",
    dateOfBirth: "08/11/1983",
    street: "333 Superhero Ave",
    city: "Sydney",
    zipCode: "2000",
  },
  {
    firstName: "Jennifer",
    lastName: "Lawrence",
    dateOfBirth: "08/15/1990",
    street: "444 Movie Star Blvd",
    city: "Los Angeles",
    zipCode: "90001",
  },
  {
    firstName: "Dwayne",
    lastName: "Johnson",
    dateOfBirth: "05/02/1972",
    street: "555 Rock Road",
    city: "Miami",
    zipCode: "33101",
  },
  {
    firstName: "Scarlett",
    lastName: "Johansson",
    dateOfBirth: "11/22/1984",
    street: "666 Black Widow St",
    city: "New York",
    zipCode: "10001",
  },
  {
    firstName: "Ryan ",
    lastName: "Reynolds",
    dateOfBirth: "10/23/1976",
    street:
      "777 Deadpool Lane 777 Deadpool Lane 777 Deadpool Lane 777 Deadpool Lane 777 Deadpool Lane 777 Deadpool Lane",
    city: "Vancouver",
    zipCode: "V6A 1B8",
  },
];
